# Generated by Django 4.2.6 on 2023-11-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('emailadress', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
