# Generated by Django 4.2.6 on 2023-11-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emailadress',
            new_name='email',
        ),
    ]
