# Generated by Django 4.2.6 on 2023-11-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='origin',
            field=models.TextField(default='exit', max_length=20),
            preserve_default=False,
        ),
    ]
