# Generated by Django 4.2.6 on 2023-11-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_products_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='origin',
            field=models.TextField(default='Kenya'),
        ),
    ]
