# Generated by Django 4.2.6 on 2023-11-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_products_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='White', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='origin',
            field=models.CharField(default='Kenya', max_length=50),
        ),
    ]
